'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowUpRight, ChevronDown, ChevronRight, Globe2, Menu, X, FileCheck2, HeartHandshake, Landmark, ShieldCheck, Sparkles, Scale, Plane, MessageCircle } from 'lucide-react'

const services = [
  { icon: Globe2, title: 'Online Marriage', href: '/online-marriage', text: 'A carefully guided online ceremony for couples who cannot be together in the same place.' },
  { icon: Plane, title: 'Remote Marriage', href: '/remote-marriage', text: 'Practical support for completing your marriage remotely, with clarity at every stage.' },
  { icon: Scale, title: 'Proxy Marriage', href: '/proxy-marriage', text: 'Understand the process, requirements and documentation for proxy marriage arrangements.' },
  { icon: HeartHandshake, title: 'Online Nikah', href: '/online-nikah', text: 'A respectful, private and structured online Nikah experience for couples worldwide.' },
  { icon: Landmark, title: 'Cross-Border Marriage', href: '/cross-border-marriage', text: 'Navigate the details that arise when two countries, two systems and one future meet.' },
  { icon: FileCheck2, title: 'Marriage Documentation', href: '/marriage-documentation', text: 'Support with certificates, apostilles, attestations and the documents that follow.' },
]

const steps = [
  ['01', 'Tell us your situation', 'Share where you are, where your partner is, and what you are hoping to arrange.'],
  ['02', 'Receive a clear pathway', 'We identify the most relevant route and explain the key requirements in plain English.'],
  ['03', 'Prepare with confidence', 'We help you organise the information and documentation needed for your next steps.'],
  ['04', 'Move forward together', 'With a considered plan in place, you can approach your marriage journey with confidence.'],
]

const faqs = [
  ['Can we arrange a marriage if we are in different countries?', 'Many couples begin their marriage journey from different countries. The right pathway depends on your circumstances, the countries involved and the type of ceremony you are considering. We can help you understand the options.'],
  ['What is the difference between online, remote and proxy marriage?', 'These terms can describe different legal and ceremonial arrangements depending on the jurisdiction. During an initial discussion, we will clarify the distinctions that matter for your situation rather than relying on a one-size-fits-all answer.'],
  ['Do you help with marriage certificates and apostilles?', 'Yes. We can guide you through the documentation journey, including certificates, apostilles, attestations and the practical steps that may follow your ceremony.'],
  ['Can you help with an online Nikah?', 'We offer respectful guidance for couples considering an online Nikah, with a focus on understanding your requirements and preparing carefully for the ceremony.'],
  ['How do we begin?', 'Start by discussing your case with us. A short initial conversation gives us the context to explain the most relevant next steps for you.'],
]

const menuCountries = [['United Kingdom','united-kingdom'],['United States','united-states'],['Canada','canada'],['Europe','europe'],['Australia','australia'],['UAE & Middle East','uae-middle-east'],['Pakistan','pakistan']]

function Logo() {
  return <a href="#top" className="flex items-center gap-3" aria-label="e-Marriages.com home">
    <span className="flex size-10 items-center justify-center rounded-full border border-champagne/50 text-champagne"><HeartHandshake className="size-5" strokeWidth={1.5} /></span>
    <span className="font-serif text-[1.2rem] tracking-[-0.02em] text-white">e-Marriages<span className="text-champagne">.com</span></span>
  </a>
}

function Header() {
  const [open, setOpen] = useState(false)
  return <header className="absolute inset-x-0 top-0 z-50">
    <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
      <Logo />
      <nav className="hidden items-center gap-8 lg:flex" aria-label="Main navigation">
        <Link href="/" className="text-sm text-white/70 transition hover:text-champagne">Home</Link>
        <div className="group/services relative py-2"><Link href="/our-services" className="text-sm text-white/70 transition hover:text-champagne">Our Services</Link><div className="invisible absolute left-0 top-full w-72 translate-y-2 rounded-xl border border-white/10 bg-navy p-2 opacity-0 shadow-2xl transition group-hover/services:visible group-hover/services:translate-y-0 group-hover/services:opacity-100">{[['Court Marriage','court-marriage'],['Online Nikah','online-nikah']].map(([label,slug])=><div key={slug} className="group/item relative"><Link href={`/${slug}`} className="flex items-center justify-between rounded-lg px-4 py-3 text-sm text-white/75 hover:bg-white/10 hover:text-champagne"><span>{label}</span><ChevronRight className="size-4"/></Link><div className="invisible absolute left-full top-0 ml-2 w-64 rounded-xl border border-white/10 bg-navy p-2 opacity-0 shadow-2xl transition group-hover/item:visible group-hover/item:opacity-100">{menuCountries.map(([country,countrySlug])=><Link key={countrySlug} href={`/services/${slug}/${countrySlug}`} className="block rounded-lg px-4 py-3 text-xs text-white/65 hover:bg-white/10 hover:text-champagne">{country}</Link>)}</div></div>)}<div className="my-2 border-t border-white/10"/><Link href="/international-marriage" className="block rounded-lg px-4 py-3 text-sm text-white/75 hover:bg-white/10 hover:text-champagne">International Marriage</Link><Link href="/marriage-documentation" className="block rounded-lg px-4 py-3 text-sm text-white/75 hover:bg-white/10 hover:text-champagne">Marriage Documentation</Link></div></div>
        <Link href="/blog" className="text-sm text-white/70 transition hover:text-champagne">Blog</Link><Link href="/about" className="text-sm text-white/70 transition hover:text-champagne">About</Link><Link href="/contact" className="text-sm text-white/70 transition hover:text-champagne">Contact Us</Link>
      </nav>
      <a href="#enquire" className="hidden items-center gap-2 rounded-full border border-champagne/70 px-5 py-2.5 text-sm text-champagne transition hover:bg-champagne hover:text-navy lg:flex">Discuss Your Case <ArrowUpRight className="size-4" /></a>
      <button onClick={() => setOpen(!open)} className="text-white lg:hidden" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open}>{open ? <X /> : <Menu />}</button>
    </div>
    {open && <div className="border-t border-white/10 bg-navy px-6 py-6 lg:hidden"><nav className="flex max-h-[75vh] flex-col gap-5 overflow-y-auto" aria-label="Mobile navigation"><Link href="/" onClick={()=>setOpen(false)} className="text-sm text-white">Home</Link><details><summary className="cursor-pointer list-none text-sm text-white">Our Services</summary><div className="mt-4 space-y-4 border-l border-white/10 pl-4">{[['Court Marriage','court-marriage'],['Online Nikah','online-nikah']].map(([label,slug])=><details key={slug}><summary className="cursor-pointer list-none text-sm text-white/75">{label}</summary><div className="mt-3 flex flex-col gap-3 border-l border-white/10 pl-4">{menuCountries.map(([country,countrySlug])=><Link key={countrySlug} href={`/services/${slug}/${countrySlug}`} onClick={()=>setOpen(false)} className="text-xs text-white/55">{country}</Link>)}</div></details>)}</div></details><Link href="/blog" onClick={()=>setOpen(false)} className="text-sm text-white">Blog</Link><Link href="/about" onClick={()=>setOpen(false)} className="text-sm text-white">About</Link><Link href="/contact" onClick={()=>setOpen(false)} className="text-sm text-white">Contact Us</Link><a href="#enquire" onClick={()=>setOpen(false)} className="mt-2 inline-flex w-fit items-center gap-2 rounded-full bg-champagne px-5 py-3 text-sm text-navy">Discuss Your Case <ArrowUpRight className="size-4" /></a></nav></div>}
  </header>
}

function SectionIntro({ eyebrow, title, text, light = false }) {
  return <div className={light ? 'text-center text-white' : 'text-center text-navy'}><p className="mb-5 text-xs font-medium uppercase tracking-[0.24em] text-champagne">{eyebrow}</p><h2 className="mx-auto max-w-3xl font-serif text-4xl leading-[1.08] tracking-[-0.03em] md:text-5xl">{title}</h2>{text && <p className={"mx-auto mt-6 max-w-2xl text-base leading-7 " + (light ? 'text-white/65' : 'text-navy/60')}>{text}</p>}</div>
}

function Footer() {
  return <footer className="bg-navy px-6 pb-8 pt-16 text-white lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-12 border-b border-white/10 pb-14 md:grid-cols-2 lg:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><Logo /><p className="mt-6 max-w-xs text-sm leading-6 text-white/55">Thoughtful guidance for couples building a life across borders.</p></div><div><p className="mb-5 text-xs uppercase tracking-[0.2em] text-champagne">Explore</p><div className="flex flex-col gap-3 text-sm text-white/60"><a href="#services" className="hover:text-white">Services</a><a href="#how-it-works" className="hover:text-white">How it works</a><a href="#coverage" className="hover:text-white">International coverage</a><a href="#faqs" className="hover:text-white">FAQs</a></div></div><div><p className="mb-5 text-xs uppercase tracking-[0.2em] text-champagne">Services</p><div className="flex flex-col gap-3 text-sm text-white/60"><span>Online marriage</span><span>Remote marriage</span><span>Online Nikah</span><span>Marriage documentation</span></div></div><div><p className="mb-5 text-xs uppercase tracking-[0.2em] text-champagne">Connect</p><div className="flex flex-col gap-3 text-sm text-white/60"><a href="#enquire" className="hover:text-white">Discuss your case</a><a href="mailto:hello@e-marriages.com" className="hover:text-white">hello@e-marriages.com</a><span>International enquiries welcome</span></div></div></div><div className="flex flex-col gap-4 pt-7 text-xs leading-5 text-white/40 md:flex-row md:items-start md:justify-between"><p>© {new Date().getFullYear()} e-Marriages.com. All rights reserved.</p><p className="max-w-xl md:text-right">Information on this website is for general guidance only and is not legal advice. Requirements vary by country and individual circumstances.</p></div></div></footer>
}

export default function Page() {
  return <div id="top" className="bg-ivory text-navy"><Header /><main>
    <section className="relative min-h-[760px] overflow-hidden bg-navy"><div className="absolute inset-0 bg-[radial-gradient(circle_at_76%_28%,rgba(201,171,112,0.18),transparent_28%)]" /><div className="mx-auto grid max-w-7xl items-center gap-12 px-6 pb-20 pt-36 lg:grid-cols-[1.08fr_0.92fr] lg:px-10 lg:pb-28 lg:pt-44"><div className="relative z-10"><p className="mb-7 flex items-center gap-3 text-xs uppercase tracking-[0.25em] text-champagne"><span className="h-px w-10 bg-champagne" />International marriage guidance</p><h1 className="max-w-3xl font-serif text-5xl leading-[1.02] tracking-[-0.045em] text-white sm:text-6xl lg:text-[5.2rem]">International marriage guidance <em className="font-light text-champagne">for couples</em> across borders.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-white/65">A considered, human approach to online and cross-border marriage services — helping you understand what comes next, wherever life has brought you together.</p><div className="mt-10 flex flex-wrap gap-4"><a href="#enquire" className="inline-flex items-center gap-3 rounded-full bg-champagne px-6 py-3.5 text-sm font-medium text-navy transition hover:bg-white">Discuss Your Case <ArrowUpRight className="size-4" /></a><a href="#services" className="inline-flex items-center gap-3 rounded-full border border-white/25 px-6 py-3.5 text-sm text-white transition hover:border-champagne hover:text-champagne">Explore our services</a></div></div><div className="relative lg:pl-10"><div className="relative aspect-[0.82] max-w-md overflow-hidden rounded-t-[12rem] rounded-b-[1.5rem] border border-white/15"><img src="/images/international-couple.png" alt="Couple standing together with marriage documents" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-navy/65 via-transparent to-transparent" /></div><div className="absolute -bottom-5 -left-1 rounded-xl border border-white/15 bg-white/10 px-5 py-4 backdrop-blur-md"><p className="text-xs uppercase tracking-[0.18em] text-champagne">Across borders</p><p className="mt-1 font-serif text-lg text-white">One future, thoughtfully arranged.</p></div></div></div><div className="absolute bottom-0 left-1/2 hidden -translate-x-1/2 items-center gap-3 text-[10px] uppercase tracking-[0.25em] text-white/35 lg:flex"><span className="h-10 w-px bg-white/25" />Scroll to explore</div></section>
    <section id="services" className="px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="What we do" title="A clearer way forward, wherever you are." text="Every couple's circumstances are different. Our role is to help you understand your options, prepare with care and move forward with confidence." /><div className="mt-16 grid gap-px overflow-hidden rounded-2xl bg-navy/10 md:grid-cols-2 lg:grid-cols-3">{services.map(({ icon: Icon, title, text, href }) => <article key={title} className="group bg-ivory p-8 transition hover:bg-white lg:p-10"><Icon className="size-7 text-champagne" strokeWidth={1.5} /><h3 className="mt-8 font-serif text-2xl">{title}</h3><p className="mt-4 text-sm leading-6 text-navy/55">{text}</p><a href={href} className="mt-8 inline-flex items-center gap-2 text-xs uppercase tracking-[0.16em] text-navy/60 transition group-hover:text-navy">Learn more <ArrowUpRight className="size-4 text-champagne" /></a></article>)}</div></div></section>
    <section id="how-it-works" className="bg-white px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="How it works" title="A thoughtful process, from first conversation to next step." text="The details may be complex. Your experience with us should feel calm, clear and personal." /><div className="mt-16 grid gap-10 md:grid-cols-2 lg:grid-cols-4">{steps.map(([number, title, text], i) => <div key={number} className="relative border-t border-navy/15 pt-6">{i < 3 && <span className="absolute right-0 top-[-1px] hidden h-px w-1/2 bg-champagne/50 lg:block" />}<p className="font-serif text-4xl text-champagne/80">{number}</p><h3 className="mt-8 font-serif text-2xl">{title}</h3><p className="mt-4 text-sm leading-6 text-navy/55">{text}</p></div>)}</div></div></section>
    <section id="coverage" className="bg-navy px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid items-end gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="mb-5 text-xs uppercase tracking-[0.24em] text-champagne">International coverage</p><h2 className="max-w-md font-serif text-4xl leading-[1.08] tracking-[-0.03em] text-white md:text-5xl">Wherever your story begins.</h2><p className="mt-6 max-w-md text-base leading-7 text-white/60">We work with couples whose lives span countries, cultures and legal systems — bringing a global perspective to every enquiry.</p></div><div className="grid grid-cols-2 gap-px border border-white/15 bg-white/15 sm:grid-cols-3">{['United Kingdom','United States','Canada','Europe','Australia','Middle East & Pakistan'].map((country, i) => <div key={country} className="bg-navy p-6 text-sm text-white/75 transition hover:bg-white/10"><span className="mb-8 block text-xs text-champagne">0{i + 1}</span>{country}</div>)}</div></div></div></section>
    <section className="px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-16 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="mb-5 text-xs uppercase tracking-[0.24em] text-champagne">The document journey</p><h2 className="max-w-md font-serif text-4xl leading-[1.08] tracking-[-0.03em] md:text-5xl">The right documents make everything clearer.</h2><p className="mt-6 max-w-md text-base leading-7 text-navy/60">From the first enquiry to the documents you may need afterwards, we help you see the full picture.</p><div className="mt-10 flex items-center gap-3 text-sm text-navy/60"><ShieldCheck className="size-5 text-champagne" /> Careful guidance at every stage</div></div><div className="flex flex-col">{['Understanding your circumstances', 'Identifying the relevant requirements', 'Preparing and reviewing documents', 'Certificate, apostille or attestation guidance'].map((item, i) => <div key={item} className="flex gap-6 border-t border-navy/15 py-7"><div className="flex size-9 shrink-0 items-center justify-center rounded-full border border-champagne text-xs text-champagne">{i + 1}</div><div><h3 className="font-serif text-2xl">{item}</h3><p className="mt-2 text-sm leading-6 text-navy/50">A considered step in creating a clear, complete path forward.</p></div></div>)}</div></div></div></section>
    <section className="bg-[#e9e4d9] px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="Why e-Marriages.com" title="Because your marriage deserves more than a checklist." text="We bring clarity to complicated situations without losing sight of the people at the heart of them." /><div className="mt-16 grid gap-10 sm:grid-cols-2 lg:grid-cols-4">{[['Human first','Your story is not a form. We listen before we advise.'],['International outlook','A global perspective for couples navigating more than one country.'],['Clear communication','Practical explanations, without unnecessary jargon or uncertainty.'],['Careful detail','A considered approach to the documents and decisions that matter.']].map(([title, text], i) => <div key={title}><Sparkles className="size-6 text-champagne" /><h3 className="mt-6 font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-navy/55">{text}</p></div>)}</div></div></section>
    <section id="faqs" className="bg-white px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-4xl"><SectionIntro eyebrow="Questions, answered" title="A little more clarity." /><div className="mt-14 divide-y divide-navy/15 border-y border-navy/15">{faqs.map(([question, answer]) => <details key={question} className="group"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 py-6 font-serif text-xl marker:content-none"><span>{question}</span><ChevronDown className="size-5 shrink-0 text-champagne transition group-open:rotate-180" /></summary><p className="max-w-2xl pb-7 pr-10 text-sm leading-6 text-navy/60">{answer}</p></details>)}</div></div></section>
    <section id="enquire" className="bg-navy px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-5xl text-center"><p className="mb-6 text-xs uppercase tracking-[0.24em] text-champagne">Begin with a conversation</p><h2 className="font-serif text-5xl leading-[1.04] tracking-[-0.04em] text-white md:text-7xl">Your next chapter<br /><em className="font-light text-champagne">starts with clarity.</em></h2><p className="mx-auto mt-7 max-w-xl text-base leading-7 text-white/60">Tell us a little about your situation and we will help you understand the most useful next step.</p><a href="mailto:hello@e-marriages.com" className="mt-10 inline-flex items-center gap-3 rounded-full bg-champagne px-7 py-4 text-sm font-medium text-navy transition hover:bg-white">Discuss Your Case <MessageCircle className="size-4" /></a></div></section>
  </main><Footer /></div>
}
