import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { SiteFooter, SiteHeader } from './site-shell'

export default function InfoPage({ eyebrow, title, intro, sections, updated = '21 September 2026' }) {
  return <div className="bg-ivory text-navy"><SiteHeader /><main>
    <section className="relative overflow-hidden bg-navy px-6 pb-20 pt-36 lg:px-10 lg:pb-28 lg:pt-44"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_25%,rgba(201,171,112,0.17),transparent_30%)]" /><div className="relative mx-auto max-w-5xl"><Link href="/" className="text-xs text-white/45 hover:text-champagne">Home / {title}</Link><p className="mb-6 mt-10 text-xs uppercase tracking-[0.24em] text-champagne">{eyebrow}</p><h1 className="font-serif text-5xl leading-[1.02] tracking-[-0.04em] text-white md:text-7xl">{title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/65">{intro}</p></div></section>
    <section className="px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-5xl gap-14 lg:grid-cols-[220px_1fr]"><aside><p className="text-xs uppercase tracking-[0.18em] text-champagne">Last updated</p><p className="mt-2 text-sm text-navy/55">{updated}</p></aside><div className="space-y-12">{sections.map(([heading, body])=><section key={heading}><h2 className="font-serif text-3xl tracking-[-0.02em]">{heading}</h2>{Array.isArray(body) ? <ul className="mt-5 space-y-3">{body.map(x=><li key={x} className="border-l border-champagne pl-5 text-sm leading-7 text-navy/60">{x}</li>)}</ul> : <p className="mt-5 text-base leading-8 text-navy/60">{body}</p>}</section>)}</div></div></section>
    <section className="bg-[#e9e4d9] px-6 py-16 lg:px-10"><div className="mx-auto flex max-w-5xl flex-col items-start justify-between gap-7 md:flex-row md:items-center"><div><p className="text-xs uppercase tracking-[0.2em] text-champagne">Need case-specific guidance?</p><h2 className="mt-3 font-serif text-3xl">Discuss the countries and intended use with us.</h2></div><Link href="/contact" className="inline-flex items-center gap-3 rounded-full bg-navy px-6 py-3.5 text-sm text-white">Contact us <ArrowUpRight className="size-4 text-champagne" /></Link></div></section>
  </main><SiteFooter /></div>
}
